# frozen_string_literal: true

module RuboCop
  module Cop
    module Rails
      # Use `assert_raises` with a `match:` keyword instead of a separate message assertion.
      #
      # It's recommended to also use these cops:
      #   1. `Lint/UselessAssignment` to remove the exception local variable if it becomes unused after this
      #       cop deletes the message assertions.
      #   2. `Style/RedundantRegexpEscape` to clean up the regexp generated by this cop.
      #
      # @safety
      #   TODO
      #
      # @example
      #   # bad
      #   e = assert_raises(FooError) { foo }
      #   assert_equal("boom", e.message)
      #
      #   # good
      #   e = assert_raises(FooError, match: /\Aboom\z/) { foo }
      #
      #   # bad
      #   e = assert_raises(FooError) { foo }
      #   assert_match(/boom/, e.message)
      #
      #   # good
      #   e = assert_raises(FooError, match: /boom/) { foo }
      class AssertRaisesMatch < Base
        include RangeHelp
        extend AutoCorrector
        extend TargetRailsVersion

        minimum_target_rails_version 7.1

        MSG = 'Use the `match:` keyword of `assert_raises` instead of a separate assertion on the exception message.'

        RESTRICT_ON_SEND = %i[assert_equal assert_match assert_includes].freeze

        ASSERT_RAISES_METHODS = %i[assert_raises assert_raise].freeze

        # Parses:
        #   1. `assert_equal(<expected_msg>, <exception_lvar>.message)`
        #   2. `assert_match(<expected_msg>, <exception_lvar>.message)`
        # @!method assert_message_equal?(node)
        #   @param node [RuboCop::AST::SendNode]
        #   @return [Array(RuboCop::AST::Node, Symbol), nil]
        def_node_matcher :assert_message_equal?, <<~PATTERN
          (send nil? {:assert_equal :assert_match} $_expected_msg (send (lvar $_exception_lvar) :message))
        PATTERN

        # `assert_includes(<lvar>.message, <match_value>)`
        # @!method assert_message_includes?(node)
        #   @param node [RuboCop::AST::SendNode]
        #   @return [Array(Symbol, RuboCop::AST::Node), nil]
        def_node_matcher :assert_message_includes?, <<~PATTERN
          (send nil? :assert_includes (send (lvar $_exception_lvar) :message) $_match_value)
        PATTERN

        # @param node [RuboCop::AST::SendNode]
        # @return [void]
        def on_send(node)
          # Find and parse the assertion over a `.message`. Return if it's not one of the expected forms.
          return unless (expected_pattern, ex_local_var_name = parse_message_assertion(node))

          assertion = node

          # Get the parent scope, where we'll check for other assertions on the same variable's message.
          return unless (parent_scope = assertion.each_ancestor(:begin).first)

          # There is more than one assertion on the exception message. Play it safe and keep them all.
          return if other_message_assertions?(parent_scope, ex_local_var_name, except: assertion)

          assert_raise = find_preceding_assert_raise(parent_scope, assertion, ex_local_var_name)
          # There's an assertion over the message, but no `assert_raises` assignment to attach it to.
          # This means it's an assertion of a `message` field of some other kind of object, which is fine.
          return unless assert_raise

          add_offense(assertion) do |corrector|
            match_source = match_source_for(assertion, expected_pattern)
            next unless match_source # This case is too complex to autocorrect. Just report the offense.

            anchor = insertion_anchor(assert_raise)
            corrector.insert_after(anchor, ", match: #{match_source}") # Add the `match:` keyword to the `assert_raises`
            corrector.remove(assertion_removal_range(assertion)) # Delete the original assertion
          end
        end

        private

        # @param node [RuboCop::AST::SendNode]
        # @return [Array(RuboCop::AST::Node, Symbol), nil]
        def parse_message_assertion(node)
          if (captures = assert_message_equal?(node))
            captures # [expected_message, ex_local_var_name]
          elsif (captures = assert_message_includes?(node))
            ex_local_var_name, expected_pattern = captures
            [expected_pattern, ex_local_var_name]
          end
        end

        # Returns true if there's more than one node in the `parent_scope` which asserts something about the `message`
        # of a variable called `variable_name`.
        # @param scope [RuboCop::AST::Node]
        # @param variable_name [Symbol]
        # @param except [RuboCop::AST::SendNode] The node to ignore when searching for other message assertions.
        # @return [Boolean]
        def other_message_assertions?(parent_scope, variable_name, except:)
          expected_node = except

          parent_scope.each_descendant(:send).any? do |send_node|
            next false if send_node.equal?(expected_node) # Skip the one we already expect.

            value, name = parse_message_assertion(send_node)
            value && name == variable_name
          end
        end

        # Finds the nearest preceding `assert_raise(s)` assigned to `variable_name`, which this cop will modify.
        #   * Any other assignments block this and make this method return `nil`.
        #   * Calls to `assert_raise` already pass `match:` also return `nil`.
        # @param scope [RuboCop::AST::Node]
        # @param node [RuboCop::AST::SendNode]
        # @param variable_name [Symbol]
        # @return [RuboCop::AST::SendNode, nil]
        def find_preceding_assert_raise(scope, node, variable_name)
          preceding_assignment = scope.children.first(node.sibling_index).reverse_each.find do |sibling|
            writes_variable?(sibling, variable_name)
          end

          return nil unless preceding_assignment&.lvasgn_type?

          assert_raises_send = unwrap_assert_raises_send(preceding_assignment.expression)
          return nil unless assert_raises_send
          return nil if already_has_match_kwarg?(assert_raises_send)

          assert_raises_send
        end

        # @param node [RuboCop::AST::Node]
        # @param variable_name [Symbol]
        # @return [Boolean] Whether the `node` contains a write to the local `expected_variable_name` anywhere within it
        def writes_variable?(node, expected_variable_name)
          return true if node.lvasgn_type? && node.lhs == expected_variable_name

          node.each_descendant(:lvasgn).any? { |n| n.lhs == expected_variable_name }
        end

        # Unwraps `assert_raises(...) { ... }` or a bare `assert_raises(...)` send.
        # @param value [RuboCop::AST::Node, nil]
        # @return [RuboCop::AST::SendNode, nil]
        def unwrap_assert_raises_send(value)
          send_node = if value.block_type? # A case like `assert_raises(FooError) { ... }`
                        value.send_node
                      else # A case like `assert_raises(FooError, &block)`
                        value
                      end
          return unless send_node.send_type?
          return unless send_node.receiver.nil? && ASSERT_RAISES_METHODS.include?(send_node.method_name)

          send_node
        end

        # @param send_node [RuboCop::AST::SendNode]
        # @return [Boolean]
        def already_has_match_kwarg?(send_node)
          kwargs = send_node.arguments.find(&:hash_type?)
          return false unless kwargs

          kwargs.each_key.any? { |k| k.sym_type? && k.value == :match }
        end

        # The `match:` keyword goes after the last positional/keyword argument but *before* an
        # explicit `&block` argument, since nothing may follow a block-pass argument in Ruby.
        # @param send_node [RuboCop::AST::SendNode]
        # @return [RuboCop::AST::Node]
        def insertion_anchor(send_node)
          unless (anchor = send_node.arguments.reject(&:block_pass_type?).last)
            raise "No arguments found? That's a bug, please report to https://github.com/rubocop/rubocop-rails/issues"
          end

          anchor
        end

        # Generates the source code to pass to the `match:` keyword argument.
        # * `assert_equal` is exact and becomes an anchored regexp
        # * `assert_match`/`assert_includes` are already substring/regexp and pass the expression through unchanged.
        # @param node [RuboCop::AST::SendNode]
        # @param match_value [RuboCop::AST::Node]
        # @return [String]
        def match_source_for(node, match_value)
          if node.method?(:assert_equal) && match_value.str_type?
            # Too complex to autocorrect and make correctly anchored.
            return nil if match_value.heredoc?

            # Good-enough approximation. `Style/RedundantRegexpEscape` can further clean up the result.
            return Regexp.new("\\A#{Regexp.escape(match_value.value)}\\z").inspect
          end

          match_value.source
        end

        # Includes the `;` separator when another statement shares the assertion's line.
        # @param node [RuboCop::AST::SendNode]
        # @return [Parser::Source::Range]
        def assertion_removal_range(node)
          range = node.source_range

          right_sibling = node.right_sibling
          if right_sibling && same_line?(range.end, right_sibling)
            return range.with(end_pos: right_sibling.source_range.begin_pos)
          end

          left_sibling = node.left_sibling
          if left_sibling && same_line?(left_sibling.source_range.end, range)
            return range.with(begin_pos: left_sibling.source_range.end_pos)
          end

          range_by_whole_lines(range, include_final_newline: true)
        end
      end
    end
  end
end
